#!/usr/bin/python3 -u

# 2022 eCTF
# Protect Firmware Tool
# Kyle Scaplen
#
# (c) 2022 The MITRE Corporation
#
# This source file is part of an example system for MITRE's 2022 Embedded System
# CTF (eCTF). This code is being provided only for educational purposes for the
# 2022 MITRE eCTF competition, and may not meet MITRE standards for quality.
# Use this code at your own risk!

import argparse
import json
import logging
# from ssl import _Cipher
from cryptography.hazmat.primitives.ciphers import algorithms, modes, Cipher
from cryptography.hazmat.backends import default_backend
from pathlib import Path
import os

from util import print_banner, FIRMWARE_ROOT, LOG_FORMAT, sign

logging.basicConfig(level=logging.INFO, format=LOG_FORMAT)
log = logging.getLogger(Path(__file__).name)


def protect_firmware(
    firmware_file: Path, version: int, release_message: str, protected_firmware: Path
):
    print_banner("SAFFIRe Firmware Protect Tool")

    # Read in the raw firmware binary
    log.info("Reading the firmware...")
    firmware_data = firmware_file.read_bytes()

    key_file = Path("/secrets/encryption_key.bin")
    key = key_file.read_bytes()[:32]
    iv = os.urandom(16)
    # Pad before signing
    padding = 32 + (32 -len(firmware_data)%32)
    firmware_data+=b"\x00"*padding

    log.info("Signing...")
    signature = sign(firmware_data)
    version_and_iv_signature = sign(version.to_bytes(4, byteorder="little") + iv)
    log.info(f"FW Signature: {signature.hex()}")
    log.info(f"Version+IV Signature: {version_and_iv_signature.hex()}")


    log.info("Encrypting...")
    # log.info(f"KEY = {key.hex()}")
    log.info(f"IV = {iv.hex()}")
    cipher = Cipher(algorithms.AES(key), modes.CBC(iv), default_backend())
    encryptor = cipher.encryptor()
    enc_fw = encryptor.update(firmware_data) + encryptor.finalize()
    log.info("Packaging the firmware...")
    log.info("Changing stuff")

    # Construct the metadata
    firmware_size = len(firmware_data)
    # enc_fw = enc.encrypt(firmware_data)
    assert len(enc_fw) == firmware_size, "Encrypted firmware is larger"
    
    # Create firmware storage structure
    data = {
        "firmware_size": firmware_size,
        "version_num": version,
        "version_and_iv_signature": version_and_iv_signature.hex(),
        "release_msg": release_message,
        "firmware": enc_fw.hex(), # encrypted firmware
        "iv": iv.hex(),
        "signature": signature.hex(),
    }

    # Write to the output file
    with protected_firmware.open("w", encoding="utf8") as fd:
        json.dump(data, fd)

    log.info("Firmware protected\n")


def main():
    # get arguments
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--firmware", help="The name of the firmware image to protect.", required=True
    )
    parser.add_argument(
        "--version", help="The version of this firmware.", type=int, required=True
    )
    parser.add_argument(
        "--release-message", help="The release message of this firmware.", required=True
    )
    parser.add_argument(
        "--output-file", help="The name of the protected firmware image.", required=True
    )

    args = parser.parse_args()

    # process command
    firmware_file = FIRMWARE_ROOT / args.firmware
    protected_firmware = FIRMWARE_ROOT / args.output_file
    protect_firmware(
        firmware_file, args.version, args.release_message, protected_firmware
    )


if __name__ == "__main__":
    main()
