#!/usr/bin/python3 -u

import ed25519
import os

signing_key, verifying_key = ed25519.create_keypair()
#aes_key = Fernet.generate_key()
# DUMMY KEY  **REMOVE**
aes_key = b'l_HnGnv5aZS1aCBZlPi4V5LjxWLjeh6uQaBRvia-Ecg='

print(f"Signature Public Key: {verifying_key.to_bytes().hex()}")

EEPROM_BLOCK_SIZE = 1<<6

with open("/secrets/ed_public_key.bin", "wb") as f:
    # f.write(b"\xdd" * EEPROM_BLOCK_SIZE)
    # Write the public key to EEPROM with padding to block size
    f.write(verifying_key.to_bytes() + b"\xdd" * 32)
    assert f.tell() == 64
with open("/secrets/ed_private_key.bin", "wb") as f:
    f.write(signing_key.to_bytes())

with open("/secrets/default_ver_signature.bin", "wb") as f:
    # Signature of the default version no.
    f.write(signing_key.sign(b"\xff\xff\xff\xff")) # Already 1 block
    assert f.tell() == 64

with open("/secrets/encryption_key.bin", "wb") as f:
    f.write(os.urandom(32)+b"\xFF"*32)
    assert f.tell() == 64

with open("/secrets/encryption_iv.bin", "wb") as f:
    f.write(os.urandom(16)+b"\xFF"*48)
    assert f.tell() == 64
