#!/usr/bin/python3 -u

import ed25519
signing_key, verifying_key = ed25519.create_keypair()

print(f"Signature Public Key: {verifying_key.to_bytes().hex()}")

EEPROM_BLOCK_SIZE = 1<<6

with open("/secrets/ed_public_key.bin", "wb") as f:
    # f.write(b"\xdd" * EEPROM_BLOCK_SIZE)
    # Write the public key to EEPROM with padding to block size
    f.write(verifying_key.to_bytes() + b"\xdd" * 32)
with open("/secrets/ed_private_key.bin", "wb") as f:
    f.write(signing_key.to_bytes())
