#!/usr/bin/python3 -u

import sys
import secrets
import os

objects = []
argv = list(sys.argv)
for arg in sys.argv:
    if arg[-2:] == ".o":
        objects.append(arg)
        argv.remove(arg)

out_objects = []
while len(objects) > 0:
    o = secrets.choice(objects)
    objects.remove(o)
    out_objects.append(o)

# Pre randomization positions:
# 13570 main
# sha256_transform 0
# sha256_final 418

argv[0] = "/usr/bin/arm-none-eabi-ld"
argv = argv[:8] + out_objects + argv[8:]
# print("New linker command:", argv)
os.execve(argv[0], argv, os.environ)
